import { Link } from 'react-router-dom';
import { ArrowLeft, AlertCircle2, CheckCircle2, Clock, Shield } from 'lucide-react';

const FAQS = [
  {
    label: 'How long do I have to request a refund?',
    items: [
      { label: '7-day window', desc: 'Full refund available within 7 days of payment' },
      { label: 'What can\'t be refunded?', desc: 'Escrow releases to verified agents are final — no refund possible' },
      { label: 'Partial refund?', desc: 'Partial refund if service was partially delivered' },
      { label: 'Manual review', desc: 'Disputed escrows go through manual review before refund' },
    ],
  },
  {
    label: 'What if the agent doesn\'t deliver?',
    items: [
      { label: 'Dispute opened', desc: 'TetherNG investigates and may reverse the release' },
      { label: 'Evidence required', desc: 'We\'ll ask for photos, messages, or call logs' },
      { label: 'Agent gets paid?', desc: 'Funds are held until dispute is resolved' },
    ],
  },
  },
  {
    label: 'Can I get my deposit back if I\'m a tenant?',
    },
  },
  {
    label: 'Yes, the deposit is safe. Here\'s exactly what happens:',
    },
    items: [
      { label: 'Step 1: Deposit', desc: 'You pay into TetherNG (not to the agent)' },
      { label: 'Step 2: Held', desc: 'Money sits safely in escrow' },
      { label: 'Step 3: Inspect', desc: 'You visit and confirm the property' },
      { label: 'Step 3. Release', desc: 'Funds go to the agent — deal is done' },
      { label: 'Confirmation is final', desc: 'No undo — this is by design to prevent fraud' },
      { label: 'Why trust this?', desc: 'Your money is held by a platform, not a person' },
    ],
  },
  },
  {
    label: 'Can I still browse without paying escrow?',
    },
  },
    },
    {
      label: 'Absolutely', desc: 'Browse, save, and message agents for free. Escrow is only for the final deal' },
    },
    },
    {
      label: 'Can I cancel escrow midway?',
    },
    },
    },
    {
      label: 'What if the agent disappears?',
    },
    },
    },
    {
      label: 'They get a warning first', desc: 'We flag suspicious behavior and may restrict their account' },
      { label: 'Restricted access', desc: 'Limited account while we investigate' },
      { label: 'Account deleted', desc: 'Permanent removal if fraud is confirmed' },
      { label: 'Data removed', desc: 'All data scrubbed within 30 days of deletion' },
    ],
  },
  },
    {
    label: 'How long does a refund take?',
    },
    },
    },
    },
    {
      label: 'Within 3-5 business days', desc: 'We aim to process refunds quickly' },
      { label: '3-5 business days', desc: 'Most refunds are automated' },
      { label: 'Manual review', desc: 'Complex cases take a little longer' },
      { label: 'Wire transfer', desc: 'Manual wire transfers are not supported — escrow only' },
      { label: 'Instant auto-release', desc: 'Standard escrows auto-release after confirmation' },
    ],
  },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
    },
  ),
};
